#!/bin/bash

echo -e "╔═══=================❖•ೋ°Services JuraganSSH Store°ೋ•❖==================═══╗"
echo -e "* menu 		: List Command Autoscript JuraganSSH Store"
echo -e "* notes 	: List of Main Commands"
echo -e ""
echo -e "╔═══====================❖•ೋ°SSH & OpenVPN°ೋ•❖°ೋ•❖=====================═══╗"
echo -e "* addssh 	: Create SSH & OpenVPN Account"
echo -e "* trialssh 	: Generate SSH & OpenVPN Trial Account"
echo -e "* renewssh 	: Extending SSH & OpenVPN Account Active Life"
echo -e "* delssh 	: Delete SSH & OpenVpn Account"
echo -e "* cekssh 	: Check User Login SSH & OpenVPN"
echo -e "* delexp 	: Clean User Expired SSH & OpenVPN"
echo -e "* ceklim 	: Displays Users Who Do Multi Login SSH"
echo -e "* member 	: Display User Lists"
echo -e "* autokill 	: Set SSH Multi Login Limit"
echo -e ""
echo -e "╔═══============❖•ೋ°V2Ray Vmess & Vless Section°ೋ•❖°ೋ•❖===============═══╗"
echo -e "* addvmess 	: Create V2RAY Vmess Websocket Account"
echo -e "* delvmess 	: Deleting V2RAY Vmess Account"
echo -e "* renewvmess 	: Extending Vmess Account Active Life"
echo -e "* cekvmess 	: Check Detail Logs Login V2RAY Vmess Account"
echo -e "* addvless 	: Create V2RAY Vless Websocket Account"
echo -e "* delvless 	: Deleting V2RAY Vless Account"
echo -e "* renewvless 	: Extending Vless Account Active Live"
echo -e "* cekvless 	: Check Detail Logs Login V2RAY Vless Account"
echo -e ""
echo -e "╔═══===========❖•ೋ°Trojan GFW & Trojan GO Section°ೋ•❖°ೋ•❖=============═══╗"
echo -e "* addtrojan 	: Create Trojan GFW Account"
echo -e "* deltrojan 	: Deleting Trojan GFW Account"
echo -e "* renewtrojan 	: Extending Trojan GFW Account Active Life"
echo -e "* cektrojan 	: Check Detail Logs Login Trojan GFW Account"
echo -e "* addtrgo	: Create Trojan GO Account"
echo -e "* deltrgo 	: Deleting Trojan GO Account"
echo -e "* renewtrgo 	: Extending Trojan GO Account Active Live"
echo -e "* cektrgo	: Check Detail Logs Login Trojan GO Account"
echo -e ""
echo -e "╔═══=========❖•ೋ°Shadowsocks & ShadowsocksR Section°ೋ•❖°ೋ•❖===========═══╗"
echo -e "* addss 	: Create Shadowsocks OBFS (SS) Account"
echo -e "* delss 	: Deleting Shadowsocks OBFS (SS) Account"
echo -e "* renewss 	: Extending Shadowsocks OBFS (SS) Account Active Life"
echo -e "* cekss 	: Check Detail Logs Login Shadowsocks OBFS (SS) Account"
echo -e "* addssr	: Create ShadowsocksR (SSR) Account"
echo -e "* delssr 	: Deleting ShadowsocksR (SSR) Account"
echo -e "* renewssr 	: Extending ShadowsocksR (SSR) Account Active Live"
echo -e "* ssr	 	: Show Other ShadowsocksR (SSR) Menu"
echo -e ""
echo -e "╔═══==============❖•ೋ°Other Type Of VPN Section°ೋ•❖°ೋ•❖================═══╗"
echo -e "* addl2tp 	: Create L2TP VPN Account"
echo -e "* dell2tp 	: Deleting L2TP VPN Account"
echo -e "* renewl2tp 	: Extending L2TP VPN Active Life"
echo -e "* addpptp 	: Create PPTP VPN Account"
echo -e "* delpptp	: Deleting PPTP VPN Account"
echo -e "* renewpptp 	: Extending PPTP VPN Active Life"
echo -e "* addsstp	: Create SSTP VPN Account"
echo -e "* delsstp 	: Deleting SSTP VPN Account"
echo -e "* renewsstp	: Extending SSTP VPN Active Life"
echo -e "* ceksstp  	: Check Detail Logs Login SSTP VPN Account"
echo -e "* addwg  	: Create Wireguard Account"
echo -e "* delwg 	: Deleting Wireguard Account"
echo -e "* renewwg 	: Extending Wireguard Active Life"
echo -e ""
echo -e "╚═══===================❖•ೋ°Service By JuraganSSH°ೋ•❖=====================═══╝"